[package]
name = "rust-cpuid"
version = "0.1.0"
authors = ["Ning Yang <csyangning@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-cpuid = "8.1.2"